### ISSUE TITLE
The model pb given by the example is too small. Can you provide a larger model pb file? Example hidden_unit=1024 and 1280

### ISSUE THREAD

**Issue by dingjingzhen** [bytedance/lightseq#24]

**Comment by Taka152** [comment]
The example is only for a quick start, if you want to check the performance of LightSeq on big models, welcome to check [performance.md](https://github.com/bytedance/lightseq/blob/master/docs/performance.md) on Transformer-big. The latency can be estimated for 1024 seq_len because they're approximately linearly related.

**Comment by dingjingzhen** [comment]
Thank you very much for your reply to me, I don't know what you said the Transformer-base model is how much of a model, hidden_unit and max_step specific is how much, I see lightseq and FasterTransformer performance contrast, at the time of batchsize and seq_len is larger, lightseq performance will be slightly a bit weak, it is also can show if the model is larger or the data volume is larger, lightseq performance will be a little weak？
![image](https://user-images.githubusercontent.com/21244263/113116940-8ad96f80-9240-11eb-8db2-12306523d7b2.png)

**Comment by Taka152** [comment]
Please check this figure and estimated latency for your model configs, sizes of the Transformer-base and Transformer-big  can be found in [paper](https://arxiv.org/pdf/1706.03762.pdf)
![image](https://user-images.githubusercontent.com/18254977/113241972-633ae380-92e2-11eb-85fb-805968cb8b8b.png)
